### ISSUE TITLE
travis vs. AppVeyor

### ISSUE THREAD

**Issue by oocx** [AnderssonPeter/CompressedStaticFiles#13]
Just out of curiosity, I was wondering why do you use travis and AppVeyor and not only just one CI build service?

**Comment by AnderssonPeter** [comment]
To be honest i don't remember it set up a few years ago!

**Comment by AnderssonPeter** [comment]
And by now i think i'm more interested in Circle CI (love docker), but i currently don't have the time to change that! :P

**Comment by oocx** [comment]
I see :). I have not used circle yet. For my own projects, I'm using Azure pipelines. 

Example: https://dev.azure.com/oocx/Oocx.AspNetCore.LinkHeader/_build?definitionId=2

**Comment by RehanSaeed** [comment]
Using both lets you run builds for Linux, Mac and Windows. Azure Pipelines lets you do all three and have also started using it more recently.

**Comment by AnderssonPeter** [comment]
I have changed over to Circle-CI, it seems to support a better integration with github than AppVeyor.
