### ISSUE TITLE
Anyway to disable image lookup?

### ISSUE THREAD

**Issue by aloksharma1** [AnderssonPeter/CompressedStaticFiles#29]
Hello,

i have my own custom implementation for image resizing/compression that compress(or resize or change formats) images on fly and save them for future use, for other static files i found your solution very useful, so if possible can you add a parameter to configuration to disable certain lookups (in my case images).

regards

**Comment by AnderssonPeter** [comment]
Hi try setting `EnableImageSubstitution` to false, this should disable the image functionality.

**Comment by AnderssonPeter** [comment]
Guessing that it solved your problem? If not respond and i will reopen.
