### ISSUE TITLE
Cannot serve brotli when using IIS Integration

### ISSUE THREAD

**Issue by nrandell** [AnderssonPeter/CompressedStaticFiles#4]
I've just had issues trying to use this when running inside Azure. I had some brotli files and they would not get served. 

I've tracked the issue down to missing content types. Pull request coming up.

I also noticed that you don't need to do app.UseStaticFiles() either. The compressed static files uses these by default.

**Comment by AnderssonPeter** [comment]
i have merged and published the nuget package, but i have no way to verify that it solved your issue or created any other issues.
