### ISSUE TITLE
Exception when path contains : character

### ISSUE THREAD

**Issue by sshumakov** [AnderssonPeter/CompressedStaticFiles#8]
Whenever path contains ":" character, exception is thrown:

```
GET https://localhost/testtest - 404
GET https://localhost/test:test - 500
```

> System.NotSupportedException

> The given path's format is not supported.

I even tried to use StaticFileOptions to limit request path to certain folder, still, the same result.

**Comment by AnderssonPeter** [comment]
My guess is that the underlying os does not support `:` in filenames.
What result are you expecting?

**Comment by cata** [comment]
@AnderssonPeter 
I've just stumbled upon this issue.  
I think the middleware should not throw an exception if the requested URL contains characters that are illegal in the underlying OS's paths/filenames.
I would expect `Invoke` to simply return `_base.Invoke(context)` in this circumstance

Consider the fact that an ASP.Net application may also serve dynamic content, in which case the URLs the server needs to handle, while valid, may contain characters that are illegal in the underlying file system.

**Comment by AnderssonPeter** [comment]
I just ported to .net standard 2.0, and i think that solved this issue?
Could you verify?

**Comment by cata** [comment]
@AnderssonPeter  - Thanks! I will try to switch back to using the CompressedStaticFiles nuget early next week and let you know if the issue is solved.

**Comment by cata** [comment]
@AnderssonPeter - a cursory examination of the code makes me think that it will still throw. To solve this on my side I put https://github.com/AnderssonPeter/CompressedStaticFiles/blob/a6e7097e3eb0aa1f36efd023344ddb016b2424e6/src/CompressedStaticFiles/CompressedStaticFileMiddleware.cs#L85-L111 in a try-catch and returned `_base.Invoke(context)` if an exception was thrown

**Comment by cata** [comment]
Sorry for not responding sooner - here's a path that will cause the current implementation to throw: `/%3A`

**Comment by AnderssonPeter** [comment]
Thanks i will check it out when i get some free time!

**Comment by AnderssonPeter** [comment]
@cata i tried to access a file with `/%3A` but i get no exception.
i ran the example project in this github and browsed to the following url http://localhost:50257/%3A

**Comment by AnderssonPeter** [comment]
@cata could you provide a example project? i can't get .net core thingies to work with CompressedStaticFiles.

The following is my try, but startup.cs does not seem to be invoked!
[Example.Net.zip](https://github.com/AnderssonPeter/CompressedStaticFiles/files/2601229/Example.Net.zip)

**Comment by cata** [comment]
@AnderssonPeter - sorry for not having responded sooner. I will look at the example this coming week
